# Explore here

In [3]:
# import libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

from sklearn.metrics import mean_squared_error, r2_score

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from pickle import dump

In [4]:
movies = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/main/tmdb_5000_movies.csv')
movies.to_csv('../data/raw/tmdb_5000_movies.csv', index=False)

movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [5]:
credits = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/main/tmdb_5000_credits.csv')
credits.to_csv('../data/raw/tmdb_5000_credits.csv', index=False)

credits.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [6]:
import os
from sqlalchemy import create_engine
from sqlalchemy import text
import pandas as pd
from dotenv import load_dotenv


# load the .env file variables
load_dotenv()

# 1) Connect to the database here using the SQLAlchemy's create_engine function
def connect():
    global engine # Esto nos permite usar una variable global llamada "engine"
    # Un "connection string" es básicamente una cadena que contiene todas las credenciales de la base de datos juntas
    connection_string = f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}/{os.getenv('DB_NAME')}?"
    print("Starting the connection...")
    engine = create_engine(connection_string)
    engine.connect()
    return engine

connect()

Starting the connection...


Engine(postgresql://postgres:***@localhost/knn-movies)

In [7]:
movies.to_sql('movies', connect(), if_exists='replace', index=False)

credits.to_sql('credits', connect(), if_exists='replace', index=False)

print("Data has been successfully loaded into the database.")



Starting the connection...
Starting the connection...
Data has been successfully loaded into the database.


In [8]:
# 3) Create a new table for the merged data

# query = text("""
# CREATE TABLE merged_data AS
# (SELECT * FROM movies
# JOIN credits USING (title));
#              """)

# with engine.connect() as conn:
#     result = conn.execute()

# print("Table 'merged_data' has been created.")



In [9]:
# 4) Load the merged data into a pandas DataFrame

merged_data = pd.read_sql_table('merged_data', engine.connect())
merged_data

title     budget  \
0                                       Avatar  237000000   
1     Pirates of the Caribbean: At World's End  300000000   
2                                      Spectre  245000000   
3                        The Dark Knight Rises  250000000   
4                                  John Carter  260000000   
...                                        ...        ...   
4804                               El Mariachi     220000   
4805                                 Newlyweds       9000   
4806                 Signed, Sealed, Delivered          0   
4807                          Shanghai Calling          0   
4808                         My Date with Drew          0   

                                                 genres  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...                                                 ...   
4804  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4805  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4806  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4807                                                 []   
4808                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4804                                               None    9367   
4805                                               None   72766   
4806  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4807                        http://shanghaicalling.com/  126186   
4808                                               None   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4804  [{"id": 5616, "name": "united states\u2013mexi...                es   
4805                                                 []                en   
4806  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4807                                                 []                en   
4808  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4804                               El Mariachi   
4805                                 Newlyweds   
4806                 Signed, Sealed, Delivered   
4807                          Shanghai Calling   
4808                         My Date with Drew   

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past

In [10]:
merged_data.to_csv('../data/raw/merged_data.csv', index=False)

print(merged_data.columns)

Index(['title', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline',
       'vote_average', 'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')


In [11]:
df = merged_data[['movie_id', 'title', 'genres', 'overview', 'keywords', 'cast', 'crew']]
print(df.head())

   movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former mi

In [12]:
df.to_csv('../data/processed/movies_mergedcleaned.csv', index=False)


In [13]:
print(df.shape)

(4809, 7)


In [14]:
import ast

# Convert the genre column from string to list of dictionaries
df['genres'] = df['genres'].apply(ast.literal_eval)
df['keywords'] = df['keywords'].apply(ast.literal_eval)
df['cast'] = df['cast'].apply(ast.literal_eval)

# Extracting names
def extract_names(items):
    return ', '.join([item['name'] for item in items])

df['genre_names'] = df['genres'].apply(extract_names)
df.drop(columns=['genres'], inplace=True)
df['keywords_names'] = df['keywords'].apply(extract_names)
df.drop(columns=['keywords'], inplace=True)
df['cast_names'] = df['cast'].apply(extract_names)
df.drop(columns=['cast'], inplace=True)


print("DataFrame with genre names column:")

print(df.columns)




C:\Users\34616\AppData\Local\Temp\ipykernel_23748\12075039.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres'] = df['genres'].apply(ast.literal_eval)
C:\Users\34616\AppData\Local\Temp\ipykernel_23748\12075039.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords'] = df['keywords'].apply(ast.literal_eval)


DataFrame with genre names column:
Index(['movie_id', 'title', 'overview', 'crew', 'genre_names',
       'keywords_names', 'cast_names'],
      dtype='object')


C:\Users\34616\AppData\Local\Temp\ipykernel_23748\12075039.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cast'] = df['cast'].apply(ast.literal_eval)
C:\Users\34616\AppData\Local\Temp\ipykernel_23748\12075039.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genre_names'] = df['genres'].apply(extract_names)
C:\Users\34616\AppData\Local\Temp\ipykernel_23748\12075039.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the docume

In [15]:
df.rename(columns={'genre_names': 'genres', 'keywords_names': 'keywords', 'cast_names': 'cast'}, inplace=True)
print(df.head())

   movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813e

C:\Users\34616\AppData\Local\Temp\ipykernel_23748\1383490972.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'genre_names': 'genres', 'keywords_names': 'keywords', 'cast_names': 'cast'}, inplace=True)


In [16]:
print(df.head())

   movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813e

In [17]:
df['genres'] = df['genres'].apply(lambda x: x.split(', ') if isinstance(x, str) else [])
df['keywords'] = df['keywords'].apply(lambda x: x.split(', ') if isinstance(x, str) else [])
df['cast'] = df['cast'].apply(lambda x: x.split(', ') if isinstance(x, str) else [])

print(df.head())



   movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813e

C:\Users\34616\AppData\Local\Temp\ipykernel_23748\2668274670.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres'] = df['genres'].apply(lambda x: x.split(', ') if isinstance(x, str) else [])
C:\Users\34616\AppData\Local\Temp\ipykernel_23748\2668274670.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['keywords'] = df['keywords'].apply(lambda x: x.split(', ') if isinstance(x, str) else [])
C:\Users\34616\AppData\Local\Temp\ipykernel_23748\2668274670.py:3: SettingWithCopyWarning: 
A value is t

In [18]:
def convert_to_list(item):
    if isinstance(item, str):
        try:
            return ast.literal_eval(item)
        except:
            return []
    elif item is None:
        return []
    else:
        return item
    
df['crew'] = df['crew'].apply(convert_to_list)
print(df['crew'])

def text_to_list(text):
    if isinstance(text, str):
        return [text]
    else:
        return []

df['overview'] = df['overview'].apply(text_to_list)
print(df['overview'])

0       [{'credit_id': '52fe48009251416c750aca23', 'de...
1       [{'credit_id': '52fe4232c3a36847f800b579', 'de...
2       [{'credit_id': '54805967c3a36829b5002c41', 'de...
3       [{'credit_id': '52fe4781c3a36847f81398c3', 'de...
4       [{'credit_id': '52fe479ac3a36847f813eaa3', 'de...
                              ...                        
4804    [{'credit_id': '52fe44eec3a36847f80b280b', 'de...
4805    [{'credit_id': '52fe487dc3a368484e0fb013', 'de...
4806    [{'credit_id': '52fe4df3c3a36847f8275ecf', 'de...
4807    [{'credit_id': '52fe4ad9c3a368484e16a36b', 'de...
4808    [{'credit_id': '58ce021b9251415a390165d9', 'de...
Name: crew, Length: 4809, dtype: object
0       [In the 22nd century, a paraplegic Marine is d...
1       [Captain Barbossa, long believed to be dead, h...
2       [A cryptic message from Bond’s past sends him ...
3       [Following the death of District Attorney Harv...
4       [John Carter is a war-weary, former military c...
                              ..

C:\Users\34616\AppData\Local\Temp\ipykernel_23748\1948580349.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crew'] = df['crew'].apply(convert_to_list)
C:\Users\34616\AppData\Local\Temp\ipykernel_23748\1948580349.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['overview'] = df['overview'].apply(text_to_list)


In [19]:
df.to_csv('../data/processed/formatted_data.csv', index=False)

In [20]:
def extract_first_three(cast_list):
    if len(cast_list) > 3:
        return cast_list[:3]
    else:
        return cast_list
    
df['cast'] = df['cast'].apply(extract_first_three)

C:\Users\34616\AppData\Local\Temp\ipykernel_23748\1531365887.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cast'] = df['cast'].apply(extract_first_three)


In [21]:
def extract_director(crew_list):
    return [member['name'] for member in crew_list if member['job'] == 'Director']

df['director'] = df['crew'].apply(extract_director)

print(df['director'])

0                                [James Cameron]
1                               [Gore Verbinski]
2                                   [Sam Mendes]
3                            [Christopher Nolan]
4                               [Andrew Stanton]
                          ...                   
4804                          [Robert Rodriguez]
4805                              [Edward Burns]
4806                               [Scott Smith]
4807                               [Daniel Hsia]
4808    [Brian Herzlinger, Jon Gunn, Brett Winn]
Name: director, Length: 4809, dtype: object


C:\Users\34616\AppData\Local\Temp\ipykernel_23748\3726170051.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['director'] = df['crew'].apply(extract_director)


In [22]:
print(df.head())

   movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In the 22nd century, a paraplegic Marine is d...   
1  [Captain Barbossa, long believed to be dead, h...   
2  [A cryptic message from Bond’s past sends him ...   
3  [Following the death of District Attorney Harv...   
4  [John Carter is a war-weary, former military c...   

                                                crew  \
0  [{'credit_id': '52fe48009251416c750aca23', 'de...   
1  [{'credit_id': '52fe4232c3a36847f800b579', 'de...   
2  [{'credit_id': '54805967c3a36829b5002c41', 'de...   
3  [{'credit_id': '52fe4781c3a36847f81398c3', 'de...   
4  [{'credit_id': '52fe479ac3a36847f813e

In [23]:
df = df.drop('crew', axis=1)

In [24]:
print(df.head())


   movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In the 22nd century, a paraplegic Marine is d...   
1  [Captain Barbossa, long believed to be dead, h...   
2  [A cryptic message from Bond’s past sends him ...   
3  [Following the death of District Attorney Harv...   
4  [John Carter is a war-weary, former military c...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

       

In [25]:
df.to_csv('../data/processed/clean_data.csv', index=False)

In [26]:
print(df.head())

   movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                            overview  \
0  [In the 22nd century, a paraplegic Marine is d...   
1  [Captain Barbossa, long believed to be dead, h...   
2  [A cryptic message from Bond’s past sends him ...   
3  [Following the death of District Attorney Harv...   
4  [John Carter is a war-weary, former military c...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

       

In [27]:
# Combine all columns into 'tags' column
def combine_to_tags(row):
    parts = []
    if isinstance(row['overview'], list):
        parts.extend(row['overview'])
    if isinstance(row['genres'], list):
        row['genres'] = [i.replace(" ", "") for i in row['genres']]
        parts.extend(row['genres'])
    if isinstance(row['cast'], list):
        row['cast'] = [i.replace(" ", "") for i in row['cast']]
        parts.extend(row['cast'])
    if isinstance(row['director'], list):
        row['director'] = [i.replace(" ", "") for i in row['director']]
        parts.extend(row['director'])
    
    return parts

df['tags'] = df.apply(combine_to_tags, axis=1)

print(df['tags'][0])

['In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.', 'Action', 'Adventure', 'Fantasy', 'ScienceFiction', 'SamWorthington', 'ZoeSaldana', 'SigourneyWeaver', 'JamesCameron']


In [28]:
df["tags"] = df["tags"].apply(lambda x: ",".join(x).replace(",", " "))
df.drop(columns = ["genres", "keywords", "cast", "director", "overview"], inplace = True)

print(df['tags'][0])
print(df.head())

In the 22nd century  a paraplegic Marine is dispatched to the moon Pandora on a unique mission  but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver JamesCameron
   movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century  a paraplegic Marine is di...  
1  Captain Barbossa  long believed to be dead  ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary  former military ca...  


In [29]:
df.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  In the 22nd century  a paraplegic Marine is di...  
1  Captain Barbossa  long believed to be dead  ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary  former military ca...

In [30]:
df.to_csv('../data/processed/final_data.csv', index=False)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(df['tags'])


print(X.toarray())

print(vectorizer.get_feature_names_out())
print(len(vectorizer.get_feature_names_out()))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['00' '000' '007' ... 'špelacolja' 'юлияснигирь' '张立']
29381


In [32]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(X)

print(similarity)


[[1.         0.34340141 0.26261287 ... 0.27386128 0.19543399 0.15899968]
 [0.34340141 1.         0.34269019 ... 0.28840267 0.30749639 0.18928248]
 [0.26261287 0.34269019 1.         ... 0.29966456 0.20995969 0.19485836]
 ...
 [0.27386128 0.28840267 0.29966456 ... 1.         0.32113081 0.18385184]
 [0.19543399 0.30749639 0.20995969 ... 0.32113081 1.         0.24859154]
 [0.15899968 0.18928248 0.19485836 ... 0.18385184 0.24859154 1.        ]]


In [33]:
new_df = df.copy()

def recommend(movie):
    movie_index = new_df[new_df["title"] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse = True , key = lambda x: x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [35]:
film = str(input("Enter a movie to find recommendations:  "))
film = film.lower()
recommend(film)


IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()




TypeError: KNeighborsClassifier.fit() missing 1 required positional argument: 'y'